;PORTC YE BAGLI YANIK LEDLER UZER?NDE B?R SONUK LED? 7. B?TTEN 0. B?TE KAYDIRAN PROGRAM SONUK LED 0. B?TE GEL?NCE DURAN PROGRAM
    LIST P=16F877A
    include "P16F877A.inc"
    SAYAC1 EQU H'0C'
    SAYAC2 EQU H'0D'
    org 0x00
    ;AYARLAMALAR
    BSF STATUS,5
    CLRF TRISC
    BCF STATUS,5
    
    MOVLW B'01111111'
    MOVWF PORTC
    BSF STATUS,0;CARRY FLAG 1 OLARAK AYARLADIK
    BASLA
    CALL GECIKME
    CALL GECIKME
    RRF PORTC,F
    BTFSC PORTC,0
    GOTO BASLA
    DONGU
    GOTO DONGU
    GECIKME
    MOVLW H'FF'
    MOVWF SAYAC1
    DONGU1
    MOVLW H'FF'
    MOVWF SAYAC2
    DONGU2
    DECFSZ SAYAC2,F
    GOTO DONGU2
    DECFSZ SAYAC1,F
    GOTO DONGU1
    RETURN
    
    
    END


